export type Market = "Россия" | "США" | "Япония" | "Китай" | "Гонконг" | "Криптовалюты";

export type Idea = {
  ticker: string;
  company: string;
  market: Market;
  sector: string;
  rating: "Покупать" | "Держать";
  current: number;
  target: number;
  currency: string;
  upside: number;
  updated: string;
  thesis: string;
  risk: string;
};

// Для обновления сайта достаточно изменить данные в этом массиве.
export const ideas: Idea[] = [
  {
    ticker: "YDEX",
    company: "Яндекс",
    market: "Россия",
    sector: "Интернет и ИИ",
    rating: "Покупать",
    current: 3642,
    target: 5884.7,
    currency: "₽",
    upside: 61.6,
    updated: "01.07.2026",
    thesis:
      "Одна из самых сильных фундаментальных историй российского рынка: двузначный рост выручки, расширение маржи и внедрение ИИ во все ключевые направления бизнеса.",
    risk:
      "Возможное введение налога на сверхприбыль и общее снижение российского рынка.",
  },
  {
    ticker: "MTSS",
    company: "МТС",
    market: "Россия",
    sector: "Телеком",
    rating: "Покупать",
    current: 181.5,
    target: 243.15,
    currency: "₽",
    upside: 33.9,
    updated: "09.07.2026",
    thesis:
      "После дивидендного гэпа котировки выглядят интересными для постепенного входа: операционный бизнес устойчив, а дивидендная история сохраняет привлекательность.",
    risk:
      "Высокие процентные расходы, капиталоёмкость бизнеса и нагрузка дивидендных выплат на денежный поток.",
  },
  {
    ticker: "HEAD",
    company: "HeadHunter",
    market: "Россия",
    sector: "HR-tech",
    rating: "Покупать",
    current: 2892,
    target: 4285.92,
    currency: "₽",
    upside: 48.2,
    updated: "29.04.2026",
    thesis:
      "Значительная часть ухудшения рынка труда уже отражена в котировках, тогда как сетевой эффект и долгосрочные преимущества платформы сохраняются.",
    risk:
      "Дальнейшее снижение числа вакансий и сокращение бюджетов работодателей на рекрутинг.",
  },
  {
    ticker: "ORCL",
    company: "Oracle",
    market: "США",
    sector: "Облака и ИИ",
    rating: "Покупать",
    current: 190,
    target: 242.15,
    currency: "$",
    upside: 27.45,
    updated: "16.06.2026",
    thesis:
      "Облачная инфраструктура быстро масштабируется, а отдача от капитальных затрат начинает проявляться в ускорении выручки и прибыли.",
    risk:
      "Резкий рост CAPEX и отрицательный свободный денежный поток повышают требования к окупаемости новых мощностей.",
  },
  {
    ticker: "7974",
    company: "Nintendo",
    market: "Япония",
    sector: "Игры",
    rating: "Покупать",
    current: 7131,
    target: 13111,
    currency: "¥",
    upside: 83.9,
    updated: "27.05.2026",
    thesis:
      "Сильный запуск Switch 2 и крупная база эксклюзивных франшиз создают основу для нового продуктового цикла.",
    risk:
      "Нормализация продаж после запуска консоли и давление аппаратного сегмента на общую маржинальность.",
  },
  {
    ticker: "XLK",
    company: "Technology Select Sector SPDR ETF",
    market: "США",
    sector: "ETF / технологии",
    rating: "Покупать",
    current: 176.6,
    target: 210,
    currency: "$",
    upside: 19,
    updated: "11.06.2026",
    thesis:
      "Прямая экспозиция на лидеров полупроводников, корпоративного ПО и ИИ-инфраструктуры после снижения технической перегретости.",
    risk:
      "Высокая концентрация портфеля и чувствительность оценок технологических компаний к ставке ФРС.",
  },
  {
    ticker: "3033",
    company: "CSOP Hang Seng TECH ETF",
    market: "Китай",
    sector: "ETF / технологии",
    rating: "Покупать",
    current: 4.45,
    target: 6.64,
    currency: "HK$",
    upside: 49,
    updated: "06.07.2026",
    thesis:
      "Отставание от широкого рынка сформировало привлекательную оценку, тогда как инвестиции Китая в ИИ, чипы и электромобили поддерживают долгосрочный потенциал.",
    risk:
      "Слабое потребление, регуляторные риски и геополитические ограничения со стороны США и их союзников.",
  },
];

export const research = [
  {
    date: "09.07.2026",
    label: "Компания",
    title: "МТС — дивидендный гэп как точка входа",
    summary:
      "Почему коррекция вернула привлекательность дивидендной истории и какие риски создают долг и процентные расходы.",
    url: "https://www.finam.ru/publications/item/mts--dividendnyy-gep-kak-tochka-vkhoda-20260710-1404/",
  },
  {
    date: "06.07.2026",
    label: "ETF",
    title: "Hang Seng TECH — отставание как возможность",
    summary:
      "Разбор состава фонда, драйверов китайского технологического сектора и ключевых уровней технической картины.",
    url: "https://www.finam.ru/publications/item/csop-hang-seng-tech-index-etf--otstavanie-ot-shirokogo-rynka-kak-khoroshaya-vozmozhnost-dlya-pokupki-20260707-1230/",
  },
  {
    date: "01.07.2026",
    label: "Компания",
    title: "Яндекс — всё лучше фундаментально",
    summary:
      "Рост выручки и маржи, монетизация ИИ и причины считать рыночную просадку избыточной.",
    url: "https://www.finam.ru/publications/item/yandeks-vse-luchshe-fundamentalno-vse-interesnee-v-aktsiyakh-20260702-1340/",
  },
  {
    date: "16.06.2026",
    label: "Компания",
    title: "Oracle — окупаемость CAPEX набирает обороты",
    summary:
      "Как рост облачной инфраструктуры меняет профиль бизнеса и почему инвестиционная программа остаётся главным риском.",
    url: "https://www.finam.ru/publications/item/oracle--okupaemost-capex-nabiraet-oboroty-20260617-1630/",
  },
];

export type CoverageItem = {
  ticker: string;
  company: string;
  market: Market;
  sector: string;
  rating: string;
  target: string;
  updated: string;
  commentDate?: string;
  potential?: string;
  tsr?: string;
  currencyCode?: string;
  analyst?: string;
  isin?: string;
  assetClass?: string;
  companyCountry?: string;
  exchangeCountry?: string;
  status: "active" | "review" | "archived";
  summary: string;
  research: { date: string; title: string; url: string };
  note: { date: string; title: string; url: string };
};

const finam = "https://www.finam.ru/publications/item";

// Архив авторского покрытия. Полные тексты остаются на Finam.ru: это сохраняет
// корректную атрибуцию и всегда ведет читателя к первоисточнику.
const legacyCoverage: CoverageItem[] = [
  {
    ticker: "3033",
    company: "CSOP Hang Seng TECH ETF",
    market: "Китай",
    sector: "ETF / технологии",
    rating: "Покупать",
    target: "HK$6,64",
    updated: "07.07.2026",
    status: "active",
    summary: "Точечная ставка на восстановление китайского технологического сектора.",
    research: { date: "04.12.2025", title: "Китайский бигтех оживает после охлаждения торговой войны", url: `${finam}/kitayskiy-bigtekh-ozhivaet-posle-okhlazhdeniya-torgovoy-voyny-kitaya-i-ssha-20251204-1721/` },
    note: { date: "07.07.2026", title: "Отставание от широкого рынка как возможность для покупки", url: `${finam}/csop-hang-seng-tech-index-etf--otstavanie-ot-shirokogo-rynka-kak-khoroshaya-vozmozhnost-dlya-pokupki-20260707-1230/` },
  },
  {
    ticker: "YDEX",
    company: "Яндекс",
    market: "Россия",
    sector: "Интернет и ИИ",
    rating: "Покупать",
    target: "₽5 884,70",
    updated: "02.07.2026",
    status: "active",
    summary: "Рост выручки, маржи и монетизации ИИ на фоне слабой динамики котировок.",
    research: { date: "18.02.2026", title: "Яндекс — первый в российском IT", url: `${finam}/yandeks--pervyy-v-rossiyskom-it-20260218-1459/` },
    note: { date: "02.07.2026", title: "Все лучше фундаментально, все интереснее в акциях", url: `${finam}/yandeks-vse-luchshe-fundamentalno-vse-interesnee-v-aktsiyakh-20260702-1340/` },
  },
  {
    ticker: "AFKS",
    company: "АФК Система",
    market: "Россия",
    sector: "Холдинг",
    rating: "Покупать",
    target: "NAV-подход",
    updated: "26.06.2026",
    status: "active",
    summary: "Дисконт к портфелю активов остается высоким из-за долга и стоимости фондирования.",
    research: { date: "26.06.2026", title: "Когда долг мешает раскрыть стоимость портфеля", url: `${finam}/afk-sistema--kogda-dolg-meshaet-raskryt-stoimost-portfelya-20260626-1655/` },
    note: { date: "26.06.2026", title: "Когда долг мешает раскрыть стоимость портфеля", url: `${finam}/afk-sistema--kogda-dolg-meshaet-raskryt-stoimost-portfelya-20260626-1655/` },
  },
  {
    ticker: "002517",
    company: "Kingnet Network",
    market: "Китай",
    sector: "Игры",
    rating: "Покупать",
    target: "CNY 19,23",
    updated: "23.06.2026",
    status: "active",
    summary: "Сильная маржинальность и рост игрового портфеля после заметного снижения акций.",
    research: { date: "20.02.2026", title: "Китайский геймдев становится все привлекательнее", url: `${finam}/kingnet-network-kitayskiy-geymdev-stanovitsya-vse-privlekatelnee-20260220-1515/` },
    note: { date: "23.06.2026", title: "Хорошие результаты на фоне падения акций", url: `${finam}/kingnet-network--ochen-khoroshie-operatsionnye-rezultaty-na-fone-padeniya-aktsiy-20260623-1755/` },
  },
  {
    ticker: "ORCL",
    company: "Oracle",
    market: "США",
    sector: "Облака и ИИ",
    rating: "Покупать",
    target: "$242,15",
    updated: "17.06.2026",
    status: "active",
    summary: "Быстрый рост облака и ИИ-инфраструктуры при высокой капиталоемкости.",
    research: { date: "17.06.2026", title: "Окупаемость CAPEX набирает обороты", url: `${finam}/oracle--okupaemost-capex-nabiraet-oboroty-20260617-1630/` },
    note: { date: "11.03.2026", title: "Взрывной рост и долгожданный отскок", url: `${finam}/vzryvnoy-rost-i-dolgozhdannyy-otskok-v-aktsiyakh-oracle-20260311-1730/` },
  },
  {
    ticker: "XLK",
    company: "Technology Select Sector SPDR ETF",
    market: "США",
    sector: "ETF / технологии",
    rating: "Покупать",
    target: "$210,00",
    updated: "11.06.2026",
    status: "active",
    summary: "Экспозиция на лидеров полупроводников, ПО и инфраструктуры искусственного интеллекта.",
    research: { date: "11.06.2026", title: "Коррекция создала точку входа в бумаги XLK", url: `${finam}/korrektsiya-v-tekhnologicheskikh-aktsiyakh-sozdala-tochku-vkhoda-v-bumagi-xlk-20260611-1919/` },
    note: { date: "11.06.2026", title: "Коррекция создала точку входа в бумаги XLK", url: `${finam}/korrektsiya-v-tekhnologicheskikh-aktsiyakh-sozdala-tochku-vkhoda-v-bumagi-xlk-20260611-1919/` },
  },
  {
    ticker: "7203",
    company: "Toyota Motor",
    market: "Япония",
    sector: "Автомобили",
    rating: "Держать",
    target: "¥2 989",
    updated: "11.06.2026",
    status: "active",
    summary: "Глобальный автопроизводитель с сильным гибридным бизнесом и ограниченным апсайдом.",
    research: { date: "14.10.2025", title: "Toyota в борьбе за американский рынок", url: `${finam}/toyota-motor-corporation-v-borbe-za-amerikanskiy-rynok-20251014-1505/` },
    note: { date: "11.06.2026", title: "Акции Toyota перестали быть слишком дорогими", url: `${finam}/aktsii-toyota-perestali-byt-slishkom-dorogimi-20260611-1830/` },
  },
  {
    ticker: "PINS",
    company: "Pinterest",
    market: "США",
    sector: "AdTech",
    rating: "Покупать",
    target: "$35,84",
    updated: "10.06.2026",
    status: "active",
    summary: "Переход к более зрелой рекламной модели и монетизации коммерческого намерения аудитории.",
    research: { date: "10.12.2025", title: "Pinterest отлично справляется с жесткой конкуренцией", url: `${finam}/pinterest-otlichno-spravlyaetsya-s-zhestkoy-konkurentsiey-20251210-1230/` },
    note: { date: "10.06.2026", title: "Pinterest переформатируется в рекламного игрока", url: `${finam}/pinterest-pereformatiruetsya-v-reklamnogo-igroka-20260610-1234/` },
  },
  {
    ticker: "CIBR",
    company: "First Trust NASDAQ Cybersecurity ETF",
    market: "США",
    sector: "ETF / кибербезопасность",
    rating: "Держать",
    target: "$88,06",
    updated: "02.06.2026",
    status: "active",
    summary: "Структурно сильная отрасль, но текущая оценка фонда уже учитывает значительную часть роста.",
    research: { date: "26.01.2026", title: "Кибербезопасность набирает важность по всему миру", url: `${finam}/kiberbezopasnost-nabiraet-vazhnost-po-vsemu-miru-20260126-1934/` },
    note: { date: "02.06.2026", title: "Кибербезопасность важна, но рынок перегрет", url: `${finam}/cibr--kiberbezopasnost-ochen-vazhna-no-rynok-peregret-20260602-1410/` },
  },
  {
    ticker: "GOOGL",
    company: "Alphabet",
    market: "США",
    sector: "Интернет и ИИ",
    rating: "Держать",
    target: "$402,77",
    updated: "29.05.2026",
    status: "active",
    summary: "Лидерство в ИИ поддерживает поиск и облако, но оценка оставляет умеренный потенциал.",
    research: { date: "10.02.2026", title: "ИИ-экосистема Alphabet разгоняется", url: `${finam}/ii-ekosistema-alphabet-razgonyaetsya-20260210-1358/` },
    note: { date: "29.05.2026", title: "Alphabet становится мировым лидером в области ИИ", url: `${finam}/alphabet-stanovitsya-mirovym-liderom-v-oblasti-ii-20260529-1323/` },
  },
  {
    ticker: "7974",
    company: "Nintendo",
    market: "Япония",
    sector: "Игры",
    rating: "Покупать",
    target: "¥13 111",
    updated: "28.05.2026",
    status: "active",
    summary: "Новый цикл Switch 2 и сильный каталог собственных игровых франшиз.",
    research: { date: "30.12.2025", title: "Акции Nintendo снизились и снова интересны", url: `${finam}/aktsii-nintendo-snizilis-i-teper-snova-interesny-20251230-1116/` },
    note: { date: "28.05.2026", title: "Акции Nintendo готовы к развороту", url: `${finam}/aktsii-nintendo-gotovy-k-razvorotu-20260528-1148/` },
  },
  {
    ticker: "MTSS",
    company: "МТС",
    market: "Россия",
    sector: "Телеком",
    rating: "Покупать",
    target: "₽243,15",
    updated: "21.05.2026",
    status: "active",
    summary: "Дивидендная история и рост экосистемы при повышенной долговой нагрузке.",
    research: { date: "11.03.2026", title: "Рост не снижает страхов вокруг долговой нагрузки", url: `${finam}/mts-rost-ne-snizhaet-strakhov-vokrug-dolgovoy-nagruzki-20260311-1417/` },
    note: { date: "21.05.2026", title: "МТС может удивить рынок", url: `${finam}/mts-mozhet-udivit-rynok-20260521-1829/` },
  },
  {
    ticker: "600570",
    company: "Hundsun Technologies",
    market: "Китай",
    sector: "Финтех ПО",
    rating: "Покупать",
    target: "CNY 33,66",
    updated: "21.05.2026",
    status: "active",
    summary: "Локальный лидер финансового ПО выигрывает от цифровизации китайского рынка капитала.",
    research: { date: "29.12.2025", title: "Hundsun Technologies выигрывает от конфликтов", url: `${finam}/hundsun-technologies-vyigryvaet-ot-konfliktov-20251229-1545/` },
    note: { date: "21.05.2026", title: "Акции вновь привлекательны для покупки", url: `${finam}/aktsii-hundsun-technologies-vnov-privlekatelny-dlya-pokupki-20260521-1325/` },
  },
  {
    ticker: "RTKM",
    company: "Ростелеком",
    market: "Россия",
    sector: "Телеком",
    rating: "Покупать",
    target: "₽75,28",
    updated: "15.05.2026",
    status: "active",
    summary: "Цифровые сервисы, облака и ЦОД постепенно становятся основными драйверами бизнеса.",
    research: { date: "10.03.2026", title: "Смена направления бизнеса приносит плоды", url: `${finam}/rostelekom-smena-napravleniya-biznesa-prinosit-plody-20260310-1814/` },
    note: { date: "15.05.2026", title: "Цифровые сервисы могут стать локомотивом", url: `${finam}/rostelekom--tsifrovye-servisy-mogut-stat-lokomotivom-dlya-kompanii-20260515-1417/` },
  },
  {
    ticker: "HEAD",
    company: "HeadHunter",
    market: "Россия",
    sector: "HR-tech",
    rating: "Покупать",
    target: "₽4 285,92",
    updated: "30.04.2026",
    status: "active",
    summary: "Лидер HR-tech проходит охлаждение рынка труда, сохраняя сетевой эффект и высокую маржу.",
    research: { date: "30.04.2026", title: "Двоякие перспективы на фоне перепроданности", url: `${finam}/headhunter--dvoyakie-perspektivy-na-fone-pereprodannosti-aktsiy-20260430-1840/` },
    note: { date: "17.03.2026", title: "Резкое охлаждение рынка труда близится к концу", url: `${finam}/khedkhanter-rezkoe-okhlazhdenie-rynka-truda-blizitsya-k-kontsu-20260317-1505/` },
  },
  {
    ticker: "MSFT",
    company: "Microsoft",
    market: "США",
    sector: "Облака и ИИ",
    rating: "Покупать",
    target: "$501,44",
    updated: "30.04.2026",
    status: "active",
    summary: "Azure и корпоративный ИИ ускоряют бизнес, а отдача от CAPEX становится заметнее.",
    research: { date: "03.12.2025", title: "Microsoft продолжает бить рекорды по капзатратам", url: `${finam}/microsoft-prodolzhaet-bit-rekordy-po-kapzatratam-20251203-1525/` },
    note: { date: "30.04.2026", title: "CAPEX перестает быть негативным фактором", url: `${finam}/microsoft--capex-perestaet-byt-negativnym-faktorom-20260430-1825/` },
  },
  {
    ticker: "FIAI",
    company: "Фабрика ПО",
    market: "Россия",
    sector: "IPO / ИИ",
    rating: "IPO",
    target: "Без цели",
    updated: "24.04.2026",
    status: "review",
    summary: "Оценка российского разработчика корпоративного ПО с фокусом на искусственный интеллект.",
    research: { date: "24.04.2026", title: "Фабрика ПО выходит на IPO", url: `${finam}/pao-fabrika-po--rossiyskiy-razrabotchik-po-s-fokusom-na-iskusstvennyy-intellekt--vykhodit-na-ipo-20260424-1757/` },
    note: { date: "24.04.2026", title: "Фабрика ПО выходит на IPO", url: `${finam}/pao-fabrika-po--rossiyskiy-razrabotchik-po-s-fokusom-na-iskusstvennyy-intellekt--vykhodit-na-ipo-20260424-1757/` },
  },
  {
    ticker: "KOMP",
    company: "SPDR S&P Kensho New Economies ETF",
    market: "США",
    sector: "ETF / новая экономика",
    rating: "Покупать",
    target: "$77,12",
    updated: "17.04.2026",
    status: "active",
    summary: "Широкая корзина компаний новой экономики, автоматизации и ИИ-инфраструктуры.",
    research: { date: "25.11.2025", title: "Хайп вокруг технологической революции не утихает", url: `${finam}/khayp-vokrug-tekhnologicheskoy-revolyutsii-ne-utikhaet-20251125-1251/` },
    note: { date: "17.04.2026", title: "Лучший фонд под восстановление IT-сектора", url: `${finam}/luchshiy-fond-pod-vosstanovlenie-it-sektora-20260417-1455/` },
  },
  {
    ticker: "BITQ",
    company: "Bitwise Crypto Industry Innovators ETF",
    market: "США",
    sector: "ETF / криптоиндустрия",
    rating: "Покупать",
    target: "$34,00",
    updated: "08.04.2026",
    status: "active",
    summary: "Экспозиция на публичные компании криптоиндустрии и новый цикл цифровых активов.",
    research: { date: "17.12.2025", title: "Обвал биткоина создал точку входа в BITQ", url: `${finam}/obval-bitkoina-sozdal-khoroshuyu-tochku-dlya-vkhoda-v-bitq-20251217-1737/` },
    note: { date: "08.04.2026", title: "Новый цикл роста BTC совсем близко", url: `${finam}/novyy-tsikl-rosta-btc-sovsem-blizko-20260408-1622/` },
  },
  {
    ticker: "CIAN",
    company: "ЦИАН",
    market: "Россия",
    sector: "Classifieds",
    rating: "На пересмотре",
    target: "₽831,74",
    updated: "26.03.2026",
    status: "review",
    summary: "Рост рентабельности и дивидендов на фоне постепенного восстановления рынка жилья.",
    research: { date: "26.03.2026", title: "Рост рентабельности создает основу для дивидендов", url: `${finam}/rost-rentabelnosti-po-itogam-goda-sozdaet-osnovu-dlya-uvelicheniya-razmera-dividendy-tsiana-20260326-1120/` },
    note: { date: "26.03.2026", title: "Рост рентабельности создает основу для дивидендов", url: `${finam}/rost-rentabelnosti-po-itogam-goda-sozdaet-osnovu-dlya-uvelicheniya-razmera-dividendy-tsiana-20260326-1120/` },
  },
  {
    ticker: "CRM",
    company: "Salesforce",
    market: "США",
    sector: "Корпоративное ПО",
    rating: "Покупать",
    target: "$321,42",
    updated: "05.03.2026",
    status: "active",
    summary: "CRM-лидер строит ИИ-экосистему и расширяет маржинальность подписочного бизнеса.",
    research: { date: "04.12.2025", title: "Salesforce строит ИИ-экосистему", url: `${finam}/salesforce-stroit-ii-ekosistemu-20251204-1157/` },
    note: { date: "05.03.2026", title: "Двузначный рост на фоне общей коррекции", url: `${finam}/salesforce--dvuznachnye-tempy-rosta-biznesa-na-fone-obshchey-korrektsii-20260305-1359/` },
  },
  {
    ticker: "6758",
    company: "Sony Group",
    market: "Япония",
    sector: "Медиа и электроника",
    rating: "Покупать",
    target: "¥5 028",
    updated: "06.02.2026",
    status: "active",
    summary: "Игры, музыка и кино поддерживают рост маржи диверсифицированной группы.",
    research: { date: "06.02.2026", title: "Sony активно работает над своей маржинальностью", url: `${finam}/sony-aktivno-rabotaet-nad-svoey-marzhinalnostyu-20260206-1450/` },
    note: { date: "06.02.2026", title: "Sony активно работает над своей маржинальностью", url: `${finam}/sony-aktivno-rabotaet-nad-svoey-marzhinalnostyu-20260206-1450/` },
  },
  {
    ticker: "WCLD",
    company: "WisdomTree Cloud Computing Fund",
    market: "США",
    sector: "ETF / облака",
    rating: "Покупать",
    target: "$43,53",
    updated: "22.01.2026",
    status: "active",
    summary: "Корзина облачных компаний после глубокой отраслевой коррекции.",
    research: { date: "22.01.2026", title: "Покупать, когда кровь течет по улицам", url: `${finam}/wcld--pokupat-kogda-krov-techet-po-ulitsam-20260122-1207/` },
    note: { date: "22.01.2026", title: "Покупать, когда кровь течет по улицам", url: `${finam}/wcld--pokupat-kogda-krov-techet-po-ulitsam-20260122-1207/` },
  },
  {
    ticker: "7211",
    company: "Mitsubishi Motors",
    market: "Япония",
    sector: "Автомобили",
    rating: "Покупать",
    target: "¥484",
    updated: "02.10.2025",
    status: "active",
    summary: "Восстановительная идея после сложного переходного периода автопроизводителя.",
    research: { date: "02.10.2025", title: "Mitsubishi Motors — возрождение близко?", url: `${finam}/mitsubishi-motors-vozrozhdenie-blizko-20251002-1159/` },
    note: { date: "02.10.2025", title: "Mitsubishi Motors — возрождение близко?", url: `${finam}/mitsubishi-motors-vozrozhdenie-blizko-20251002-1159/` },
  },
  {
    ticker: "DIS",
    company: "Walt Disney",
    market: "США",
    sector: "Медиа",
    rating: "Снято с покрытия",
    target: "—",
    updated: "03.02.2026",
    status: "archived",
    summary: "Покрытие завершено из-за стагнации бизнеса и недостатка инвестиционных драйверов.",
    research: { date: "03.02.2026", title: "Walt Disney стагнирует — снимаем с покрытия", url: `${finam}/walt-disney-company-stagniruet-poetomu-my-snimaem-bumagi-dis-s-pokrytiya-20260203-1818/` },
    note: { date: "03.02.2026", title: "Walt Disney стагнирует — снимаем с покрытия", url: `${finam}/walt-disney-company-stagniruet-poetomu-my-snimaem-bumagi-dis-s-pokrytiya-20260203-1818/` },
  },
  {
    ticker: "DELI",
    company: "Делимобиль",
    market: "Россия",
    sector: "Мобильность",
    rating: "Покрытие приостановлено",
    target: "—",
    updated: "29.12.2025",
    status: "archived",
    summary: "Покрытие приостановлено на фоне долговых рисков и ухудшения операционной модели.",
    research: { date: "29.12.2025", title: "Приостанавливаем покрытие акций Делимобиля", url: `${finam}/priostanavlivaem-analiticheskoe-pokrytie-aktsiy-delimobil-20251229-1624/` },
    note: { date: "29.12.2025", title: "Приостанавливаем покрытие акций Делимобиля", url: `${finam}/priostanavlivaem-analiticheskoe-pokrytie-aktsiy-delimobil-20251229-1624/` },
  },
];

const commonFacts = {
  analyst: "Лозовой Дмитрий",
} as const;

// Параметры покрытия сверены с выгрузкой аналитика. Ключом остается старый
// короткий тикер, чтобы сохранить найденные ссылки и описания материалов.
const coverageCorrections: Record<string, Partial<CoverageItem>> = {
  "3033": {
    ...commonFacts,
    ticker: "3033.HK",
    company: "CSOP Hang Seng TECH Index ETF",
    market: "Гонконг",
    target: "HK$6,64",
    updated: "06.07.2026",
    commentDate: "06.07.2026",
    potential: "42,9%",
    tsr: "42,9%",
    currencyCode: "HKD",
    isin: "HK0000642568",
    assetClass: "ETF / акции",
    companyCountry: "Китай",
    exchangeCountry: "Гонконг",
  },
  YDEX: {
    ...commonFacts,
    ticker: "YDEX.MM",
    target: "₽5 884,70",
    updated: "01.07.2026",
    commentDate: "01.07.2026",
    potential: "63,4%",
    tsr: "69,5%",
    currencyCode: "RUB",
    isin: "RU000A107T19",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
  },
  AFKS: {
    ...commonFacts,
    ticker: "AFKS.MM",
    target: "₽16,18",
    updated: "26.06.2026",
    commentDate: "26.06.2026",
    potential: "62,2%",
    tsr: "62,2%",
    currencyCode: "RUB",
    isin: "RU000A0DQZE3",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
  },
  "002517": {
    ...commonFacts,
    ticker: "002517.SZ",
    target: "CNY 19,23",
    updated: "19.06.2026",
    commentDate: "19.06.2026",
    potential: "17,8%",
    tsr: "19,3%",
    currencyCode: "CNY",
    isin: "CNE100000XB5",
    assetClass: "Акции",
    companyCountry: "Китай",
    exchangeCountry: "Китай",
  },
  ORCL: {
    ...commonFacts,
    ticker: "ORCL.K",
    target: "$242,15",
    updated: "16.06.2026",
    commentDate: "16.06.2026",
    potential: "72,4%",
    tsr: "73,8%",
    currencyCode: "USD",
    isin: "US68389X1054",
    assetClass: "Акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  XLK: {
    ...commonFacts,
    company: "Technology Select Sector SPDR Fund",
    target: "$210,00",
    updated: "11.06.2026",
    commentDate: "11.06.2026",
    potential: "15,8%",
    tsr: "16,2%",
    currencyCode: "USD",
    isin: "US81369Y8030",
    assetClass: "ETF / акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  "7203": {
    ...commonFacts,
    ticker: "7203.T",
    target: "¥2 989,00",
    updated: "10.06.2026",
    commentDate: "10.06.2026",
    potential: "5,8%",
    tsr: "9,7%",
    currencyCode: "JPY",
    isin: "JP3633400001",
    assetClass: "Акции",
    companyCountry: "Япония",
    exchangeCountry: "Япония",
  },
  PINS: {
    ...commonFacts,
    ticker: "PINS.K",
    target: "$35,84",
    updated: "09.06.2026",
    commentDate: "09.06.2026",
    potential: "59,1%",
    tsr: "59,1%",
    currencyCode: "USD",
    isin: "US72352L1061",
    assetClass: "Акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  CIBR: {
    ...commonFacts,
    ticker: "CIBR.O",
    target: "$88,06",
    updated: "01.06.2026",
    commentDate: "01.06.2026",
    potential: "-3,9%",
    tsr: "-3,5%",
    currencyCode: "USD",
    isin: "US33734X8469",
    assetClass: "ETF / акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  GOOGL: {
    ...commonFacts,
    ticker: "GOOGL.O",
    target: "$352,41",
    updated: "28.05.2026",
    commentDate: "28.05.2026",
    potential: "-2,6%",
    tsr: "-2,4%",
    currencyCode: "USD",
    isin: "US02079K3059",
    assetClass: "Акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  "7974": {
    ...commonFacts,
    ticker: "7974.T",
    target: "¥13 111",
    updated: "27.05.2026",
    commentDate: "27.05.2026",
    potential: "84,1%",
    tsr: "87,0%",
    currencyCode: "JPY",
    isin: "JP3756600007",
    assetClass: "Акции",
    companyCountry: "Япония",
    exchangeCountry: "Япония",
  },
  "600570": {
    ...commonFacts,
    ticker: "600570.SS",
    target: "CNY 33,66",
    updated: "20.05.2026",
    commentDate: "20.05.2026",
    potential: "59,1%",
    tsr: "60,2%",
    currencyCode: "CNY",
    isin: "CNE000001GD5",
    assetClass: "Акции",
    companyCountry: "Китай",
    exchangeCountry: "Китай",
  },
  RTKM: {
    ...commonFacts,
    ticker: "RTKM.MM",
    company: "Ростелеком ао",
    target: "₽75,28",
    updated: "14.05.2026",
    commentDate: "14.05.2026",
    potential: "79,1%",
    tsr: "85,6%",
    currencyCode: "RUB",
    isin: "RU0008943394",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
  },
  MSFT: {
    ...commonFacts,
    ticker: "MSFT.O",
    target: "$501,44",
    updated: "30.04.2026",
    commentDate: "30.04.2026",
    potential: "30,8%",
    tsr: "31,9%",
    currencyCode: "USD",
    isin: "US5949181045",
    assetClass: "Акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  HEAD: {
    ...commonFacts,
    ticker: "HEAD.MM",
    company: "Хэдхантер",
    target: "₽4 285,92",
    updated: "29.04.2026",
    commentDate: "29.04.2026",
    potential: "64,3%",
    tsr: "79,7%",
    currencyCode: "RUB",
    isin: "RU000A107662",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
  },
  FIAI: {
    ...commonFacts,
    company: "FabricaONE.AI / Фабрика ПО",
    target: "₽41,57",
    updated: "23.04.2026",
    commentDate: "23.04.2026",
    potential: "66,3% к цене IPO",
    tsr: "66,3%",
    currencyCode: "RUB",
    isin: "RU000A10B032",
    assetClass: "Акции / IPO",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
    rating: "IPO-оценка",
    status: "review",
  },
  KOMP: {
    ...commonFacts,
    ticker: "KOMP.K",
    company: "SPDR S&P Kensho New Economies Composite ETF",
    target: "$77,12",
    updated: "17.04.2026",
    commentDate: "17.04.2026",
    potential: "13,3%",
    tsr: "14,8%",
    currencyCode: "USD",
    isin: "US78468R6484",
    assetClass: "ETF / акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  CRM: {
    ...commonFacts,
    target: "$275,41",
    updated: "15.04.2026",
    commentDate: "15.04.2026",
    potential: "65,3%",
    tsr: "66,4%",
    currencyCode: "USD",
    isin: "US79466L3024",
    assetClass: "Акции",
    companyCountry: "США",
    exchangeCountry: "США",
    research: { date: "15.04.2026", title: "Падение акций не отменяет улучшения бизнеса", url: `${finam}/salesforce-padenie-aktsiy-ne-otmenyaet-uluchsheniya-biznesa-20260415-1425/` },
    note: { date: "15.04.2026", title: "Падение акций не отменяет улучшения бизнеса", url: `${finam}/salesforce-padenie-aktsiy-ne-otmenyaet-uluchsheniya-biznesa-20260415-1425/` },
  },
  BITQ: {
    ...commonFacts,
    ticker: "BITQ.K",
    target: "$34,00",
    updated: "08.04.2026",
    commentDate: "08.04.2026",
    potential: "42,7%",
    tsr: "43,3%",
    currencyCode: "USD",
    isin: "US09175C1036",
    assetClass: "ETF / акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
  CIAN: {
    ...commonFacts,
    ticker: "CNRU.MM",
    target: "₽831,74",
    updated: "02.04.2026",
    commentDate: "02.04.2026",
    potential: "65,4%",
    tsr: "83,2%",
    currencyCode: "RUB",
    isin: "RU000A10ANA1",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
    rating: "Покупать",
    status: "active",
    research: { date: "03.04.2026", title: "Отсутствие долга как конкурентное преимущество", url: `${finam}/tsian-otsutstvie-dolga-kak-konkurentnoe-preimushchestvo-20260403-1724/` },
    note: { date: "03.04.2026", title: "Отсутствие долга как конкурентное преимущество", url: `${finam}/tsian-otsutstvie-dolga-kak-konkurentnoe-preimushchestvo-20260403-1724/` },
  },
  "7211": {
    ...commonFacts,
    ticker: "7211.T",
    target: "¥484,00",
    updated: "24.03.2026",
    commentDate: "24.03.2026",
    potential: "46,4%",
    tsr: "49,5%",
    currencyCode: "JPY",
    isin: "JP3899800001",
    assetClass: "Акции",
    companyCountry: "Япония",
    exchangeCountry: "Япония",
    research: { date: "24.03.2026", title: "Ставка на восстановление маржинальности", url: `${finam}/mitsubishi-motors--stavka-na-vosstanovlenie-marzhinalnosti-20260324-1531/` },
    note: { date: "24.03.2026", title: "Ставка на восстановление маржинальности", url: `${finam}/mitsubishi-motors--stavka-na-vosstanovlenie-marzhinalnosti-20260324-1531/` },
  },
  MTSS: {
    ...commonFacts,
    ticker: "MTSS.MM",
    target: "₽243,15",
    updated: "10.03.2026",
    commentDate: "10.03.2026",
    potential: "36,6%",
    tsr: "56,3%",
    currencyCode: "RUB",
    isin: "RU0007775219",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
    rating: "Держать",
  },
  "6758": {
    ...commonFacts,
    ticker: "6758.T",
    company: "Sony",
    target: "¥5 028,00",
    updated: "05.02.2026",
    commentDate: "05.02.2026",
    potential: "47,5%",
    tsr: "48,6%",
    currencyCode: "JPY",
    isin: "JP3435000009",
    assetClass: "Акции",
    companyCountry: "Япония",
    exchangeCountry: "Япония",
  },
  WCLD: {
    ...commonFacts,
    ticker: "WCLD.O",
    target: "$43,53",
    updated: "21.01.2026",
    commentDate: "21.01.2026",
    potential: "28,9%",
    tsr: "28,9%",
    currencyCode: "USD",
    isin: "US97717Y6914",
    assetClass: "ETF / акции",
    companyCountry: "США",
    exchangeCountry: "США",
  },
};

const additionalCoverage: CoverageItem[] = [
  {
    ...commonFacts,
    ticker: "ETH-USD",
    company: "Ethereum",
    market: "Криптовалюты",
    sector: "Цифровые активы",
    rating: "Покупать",
    target: "$2 160",
    updated: "10.07.2026",
    commentDate: "10.07.2026",
    currencyCode: "USD",
    assetClass: "Криптовалюта",
    companyCountry: "Глобальный актив",
    exchangeCountry: "Глобальный рынок",
    status: "active",
    summary: "Ethereum сохраняет потенциал восстановления к целевому уровню $2 160 на фоне развития экосистемы, роста активности в децентрализованных приложениях и улучшения глобальной ликвидности. При этом высокая волатильность, конкуренция других сетей и зависимость от общего состояния криптовалютного рынка остаются ключевыми рисками.",
    research: { date: "10.07.2026", title: "Мнение автора, основанное на техническом анализе и макроэкономическом прогнозе", url: "#" },
    note: { date: "10.07.2026", title: "Мнение автора, основанное на техническом анализе и макроэкономическом прогнозе", url: "#" },
  },
  {
    ...commonFacts,
    ticker: "BTC-USD",
    company: "Bitcoin",
    market: "Криптовалюты",
    sector: "Цифровые активы",
    rating: "Покупать",
    target: "$82 000",
    updated: "10.07.2026",
    commentDate: "10.07.2026",
    currencyCode: "USD",
    assetClass: "Криптовалюта",
    companyCountry: "Глобальный актив",
    exchangeCountry: "Глобальный рынок",
    status: "active",
    summary: "После глубокой коррекции Bitcoin торгуется заметно ниже целевого уровня $82 000. Ограниченная эмиссия, институциональный спрос и восстановление интереса к цифровым активам создают потенциал роста, однако высокая волатильность и чувствительность к глобальной ликвидности сохраняются.",
    research: { date: "08.04.2026", title: "Мнение автора, основанное на техническом анализе и макроэкономическом прогнозе", url: `${finam}/novyy-tsikl-rosta-btc-sovsem-blizko-20260408-1622/` },
    note: { date: "08.04.2026", title: "Мнение автора, основанное на техническом анализе и макроэкономическом прогнозе", url: `${finam}/novyy-tsikl-rosta-btc-sovsem-blizko-20260408-1622/` },
  },
  {
    ...commonFacts,
    ticker: "RTKM_p.MM",
    company: "Ростелеком ап",
    market: "Россия",
    sector: "Телеком",
    rating: "Покупать",
    target: "₽75,28",
    updated: "14.05.2026",
    commentDate: "14.05.2026",
    potential: "74,3%",
    tsr: "80,5%",
    currencyCode: "RUB",
    isin: "RU0009046700",
    assetClass: "Акции",
    companyCountry: "Россия",
    exchangeCountry: "Россия",
    status: "active",
    summary: "Привилегированные акции цифрового телеком-холдинга с дивидендным потенциалом.",
    research: { date: "10.03.2026", title: "Смена направления бизнеса приносит плоды", url: `${finam}/rostelekom-smena-napravleniya-biznesa-prinosit-plody-20260310-1814/` },
    note: { date: "15.05.2026", title: "Цифровые сервисы могут стать локомотивом", url: `${finam}/rostelekom--tsifrovye-servisy-mogut-stat-lokomotivom-dlya-kompanii-20260515-1417/` },
  },
  {
    ...commonFacts,
    ticker: "9999.HK",
    company: "NetEase",
    market: "Гонконг",
    sector: "Игры и интернет",
    rating: "Покупать",
    target: "HK$276,95",
    updated: "14.07.2026",
    commentDate: "14.07.2026",
    potential: "32,0%",
    tsr: "34,6%",
    currencyCode: "HKD",
    isin: "KYG6427A1022",
    assetClass: "Акции",
    companyCountry: "Китай",
    exchangeCountry: "Гонконг",
    status: "active",
    summary: "Китайский игровой лидер с сильным портфелем хитов и устойчивой денежной позицией.",
    research: { date: "14.07.2026", title: "Китайский геймдев все лучше и лучше", url: `${finam}/netease--kitayskiy-geymdev-vse-luchshe-i-luchshe-20260714-1148/` },
    note: { date: "14.07.2026", title: "Китайский геймдев все лучше и лучше", url: `${finam}/netease--kitayskiy-geymdev-vse-luchshe-i-luchshe-20260714-1148/` },
  },
  {
    ...commonFacts,
    ticker: "NTES.O",
    company: "NetEase (ADR)",
    market: "США",
    sector: "Игры и интернет",
    rating: "Покупать",
    target: "$176,63",
    updated: "14.07.2026",
    commentDate: "14.07.2026",
    potential: "34,4%",
    tsr: "37,1%",
    currencyCode: "USD",
    isin: "US64110W1027",
    assetClass: "Акции",
    companyCountry: "Китай",
    exchangeCountry: "США",
    status: "active",
    summary: "Американские депозитарные расписки китайского игрового лидера NetEase.",
    research: { date: "14.07.2026", title: "Китайский геймдев все лучше и лучше", url: `${finam}/netease--kitayskiy-geymdev-vse-luchshe-i-luchshe-20260714-1148/` },
    note: { date: "14.07.2026", title: "Китайский геймдев все лучше и лучше", url: `${finam}/netease--kitayskiy-geymdev-vse-luchshe-i-luchshe-20260714-1148/` },
  },
];

function dateValue(value: string) {
  const [day, month, year] = value.split(".").map(Number);
  return Date.UTC(year, month - 1, day);
}

export const coverage: CoverageItem[] = [
  ...legacyCoverage.map((item) => ({
    ...item,
    ...coverageCorrections[item.ticker],
  })),
  ...additionalCoverage,
].sort((a, b) => dateValue(b.updated) - dateValue(a.updated));
